# Generated by Django 6.0.4 on 2026-05-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0002_seed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="is_open",
            field=models.BooleanField(
                default=True, help_text="Anyone can join without an invite"
            ),
        ),
    ]
